# Copied from https://github.com/nim-lang/Nim/wiki/TravisCI
language: c
env:
  # Nim versions to test against
  - CHOOSENIM_CHOOSE_VERSION=devel
  - CHOOSENIM_CHOOSE_VERSION=0.19.4
  - CHOOSENIM_CHOOSE_VERSION=0.19.0
  - CHOOSENIM_CHOOSE_VERSION=0.18.0
  - CHOOSENIM_CHOOSE_VERSION=0.17.2
  - CHOOSENIM_CHOOSE_VERSION=0.16.0
  - CHOOSENIM_CHOOSE_VERSION=0.15.2

compiler:
  # Compiler shouldn't matter - we're writing macros here
  - gcc
install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
before_script:
  - set -e
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=/home/travis/.nimble/bin:$PATH
script:
  - nim --cc:$CC tests
cache:
  directories:
    - nim
branches:
  except:
    - gh-pages
